pages:
  stage: deploy
  script:
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm install -g gulp
  artifacts:
    paths:
    - dist
  only:
  - master
