baseurl = "https://nomoreads.org/"
languageCode = "en-us"
title = "No More Ads"
theme = "type"
paginate = 1

[params]
	avatar = "favicon-128x128.png"
	headerText = "There are better ways of monetizing apps, services, and websites than through advertisements."
	copyright = "[Uncopyright](https://uncopyright.org/) &middot; [Our Manifesto](/manifesto)"

	[params.social]
		rss = true
		homepage = true
		email = "contact@nomoreads.org"
